name: Run postman tests

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        description: 'Run postman collection with newman'
        default: 'newman'
        required: true
        type: string
        
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install newman 
        run: npm install -g newman 

      - name: Run get user collection 
        run: newman run postman/collections/GET\ users.json 
